<?php
/**
 * MealApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Čili Pica Restaurant
 *
 * This server allow client to browse available food and order it.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nerijus@eimanavicius.lt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Server\Tests\Api;

use OpenAPI\Server\Configuration;
use OpenAPI\Server\ApiClient;
use OpenAPI\Server\ApiException;
use OpenAPI\Server\ObjectSerializer;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * MealApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Api
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */
class MealApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addMeal
     *
     * Add a new meal to the restaurant.
     *
     */
    public function testAddMeal()
    {
        $client = static::createClient();

        $path = '/meal';

        $crawler = $client->request('POST', $path);
    }

    /**
     * Test case for deleteMeal
     *
     * Deletes a meal.
     *
     */
    public function testDeleteMeal()
    {
        $client = static::createClient();

        $path = '/meal/{mealId}';
        $pattern = '{mealId}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
    }

    /**
     * Test case for findMealsByStatus
     *
     * Finds Meals by status.
     *
     */
    public function testFindMealsByStatus()
    {
        $client = static::createClient();

        $path = '/meal/findByStatus';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getMealById
     *
     * Find meal by ID.
     *
     */
    public function testGetMealById()
    {
        $client = static::createClient();

        $path = '/meal/{mealId}';
        $pattern = '{mealId}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for updateMeal
     *
     * Update an existing meal.
     *
     */
    public function testUpdateMeal()
    {
        $client = static::createClient();

        $path = '/meal';

        $crawler = $client->request('PUT', $path);
    }

    /**
     * Test case for updateMealWithForm
     *
     * Updates a meal in the restaurant with form data.
     *
     */
    public function testUpdateMealWithForm()
    {
        $client = static::createClient();

        $path = '/meal/{mealId}';
        $pattern = '{mealId}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('POST', $path);
    }

    /**
     * Test case for uploadFile
     *
     * uploads an image.
     *
     */
    public function testUploadFile()
    {
        $client = static::createClient();

        $path = '/meal/{mealId}/uploadImage';
        $pattern = '{mealId}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('POST', $path);
    }

    protected function genTestData($regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast); 
    }
}
